services:

  n8n:
    # image: docker.n8n.io/n8nio/n8n
    image: docker.n8n.io/n8nio/n8n@sha256:72e962537379dcefeb63a01397a099576e2e89a365f5a75efb8a5ad5bc5cff6a
    restart: unless-stopped
    container_name: n8n
    tty: true
    stdin_open: true
    ports:
      - "5678:5678"
    environment:
      - N8N_BASE_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      # - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - N8N_MIGRATE_FS_STORAGE_PATH=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - automation_net
    extra_hosts:
         - "host.docker.internal:host-gateway"

  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   container_name: cloudflared
  #   restart: unless-stopped
  #   command: tunnel run
  #   environment:
  #     - TUNNEL_TOKEN="YOUR TOKEN HERE"
  #   networks:
  #     - automation_net
  #   depends_on:
  #     - n8n

  n8n-reddit-api:
    image: reddit-api-image:latest 
    container_name: n8n-reddit-api
    restart: unless-stopped
    volumes:
      # source: ./.env (The file path on the host, relative to this docker-compose file)
      # ro:true (Ensures the file is mounted read-only, preventing the container from modifying it)
      - ./secrets.env/redditapi-secrets.json:/secrets/redditapi-secrets.json:ro
    ports:
      - "2222:22" # Host port: 2222, Container port: 22
    networks:
      - automation_net
  
  n8n-scrapy-api:
    image: scrapy-api-image:latest 
    container_name: n8n-scrapy-api
    restart: unless-stopped
    ports:
      - "2223:22" # Host port: 2222, Container port: 23
    networks:
      - automation_net

networks:
  automation_net:
    driver: bridge

volumes:
  n8n_data:
    external: true